// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/*.config.*',
      // Generated by Next on every build; its triple-slash references are the
      // required form, so linting it only ever produces noise.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // The spec is explicit: no `any`. These are errors, not warnings.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'off', // requires type-aware linting; enabled per-package
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },
  {
    // Seeds, scripts and tests legitimately log and use loose typing at the edges.
    files: ['**/*.test.ts', '**/scripts/**', '**/seed*.ts', '**/vitest.config.ts'],
    rules: { 'no-console': 'off', '@typescript-eslint/no-explicit-any': 'off' },
  },
  {
    // NestJS reads constructor parameter types at runtime from the metadata
    // `emitDecoratorMetadata` writes, and that metadata only exists for imports
    // that survive to runtime. `consistent-type-imports` rewrites an injected
    // class to `import type`, the metadata becomes `Object`, and dependency
    // injection fails at boot with "Nest can't resolve dependencies".
    // The two features cannot both be on in this package.
    files: ['apps/api/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },
  prettier,
);
